### ISSUE TITLE
Dust >= 2.5 has a toggle whitespace flag

### ISSUE THREAD

**Issue by sethkinast** [klei/dust#20]
Hi,

Thanks for your support of Dust.

As of Dust 2.5.0, you can set `dust.config.whitespace = true` to respect whitespace (`false` is still the default setting for now).

Using this config flag instead of manually clobbering the optimizer avoids a couple bugs [like this one](https://github.com/linkedin/dustjs/issues/498).

**Comment by joakimbeng** [comment]
Thanks!
